name: Build CV
on:
  workflow_dispatch:
  push:
    tags:
      - '**'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      - name: Create the build directory
        run: |
          mkdir build
      - name: Build Typst files
        run: |
          typst compile main.typ --font-path fonts/ build/vvelicodnii-cv.pdf
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: |
            pages deploy build/ --project-name=vvelicodnii-cv
